// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace angular.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("T_Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("T_Category");
                });

            modelBuilder.Entity("T_Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("fk_Listid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("fk_Productid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("fk_Listid");

                    b.HasIndex("fk_Productid");

                    b.ToTable("T_Item");
                });

            modelBuilder.Entity("T_List", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("T_List");
                });

            modelBuilder.Entity("T_Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("fk_Categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("fk_Categoryid");

                    b.ToTable("T_Product");
                });

            modelBuilder.Entity("T_Item", b =>
                {
                    b.HasOne("T_List", "fk_List")
                        .WithMany("fk_Item")
                        .HasForeignKey("fk_Listid");

                    b.HasOne("T_Product", "fk_Product")
                        .WithMany()
                        .HasForeignKey("fk_Productid");

                    b.Navigation("fk_List");

                    b.Navigation("fk_Product");
                });

            modelBuilder.Entity("T_Product", b =>
                {
                    b.HasOne("T_Category", "fk_Category")
                        .WithMany("fk_Product")
                        .HasForeignKey("fk_Categoryid");

                    b.Navigation("fk_Category");
                });

            modelBuilder.Entity("T_Category", b =>
                {
                    b.Navigation("fk_Product");
                });

            modelBuilder.Entity("T_List", b =>
                {
                    b.Navigation("fk_Item");
                });
#pragma warning restore 612, 618
        }
    }
}
